services:
  postgres:
    image: postgres:15
    container_name: bizify-postgres
    environment:
      POSTGRES_USER: bizify
      POSTGRES_PASSWORD: bizify_password
      POSTGRES_DB: bizify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bizify"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: bizify-backend
    environment:
      DATABASE_URL: postgresql://bizify:bizify_password@postgres:5432/bizify
      SECRET_KEY: your_secret_key_here
      DOCKER_ENV: "true"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to be ready...' &&
        pip install reportlab==4.0.4 &&
        python -m migrations.create_tables &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: bizify-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api
      - WDS_SOCKET_PORT=3000

volumes:
  postgres_data:
